import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems:'center',
    backgroundColor: '#009688FF',
    padding: 8,
  },
  titulo: {
    color: 'white',
    fontSize: 20,
    textAlign: 'center',
    fontWeight:600
  },
  caixaTexto: {
    width: 380,
    height: 50,
    backgroundColor: 'white',
    borderRadius: 8,
    textAlign:'center',
  },
  card: {
    backgroundColor: '#009688FF',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    padding:5,
  },
  btnCaclular:{
    alignItems:'center',
    justifyContent:'center',
    backgroundColor:'#FE9800FF',
    width:230,
    height: 45,
    borderRadius: 8,
  },
  textBtn:{
    color:'#ffffff',
    fontSize:20,
    fontWeight:700,
  },
  telaImagemPrincipal:{
    display:'flex',
    alignItems:'center',
    justifyContent:'center',
    width:380,
    height:'75%',
    borderRadius:8,
    borderWidth:2,
    borderColor:'white'

  },
  imagemPrincial:{
    width:'95%',
    height:'95%',
  }
});


export const stylesResultado = StyleSheet.create({
  telaResultadoOculto:{
    display:'none',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 150, 136,0.95)',
    width: '100%',
    height: '100%',
    position: 'absolute',
    zIndex: 1,
    gap: 5,
  },
  telaResultado: {
    display:'flex',
    alignItems:'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 150, 136,0.95)',
    width: '100%',
    height: '100%',
    position: 'absolute',
    zIndex: 1,
    gap: 5,
  },
  notificarAnimadoCard: {
    display:'flex',
    backgroundColor: '#FE9800FF',
    width: 140,
    height: 35,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    position: 'absolute',
    zIndex: 2,
    top: 60,
    left: 5,
  },
    notificarAnimadoCardVerde: {
    display:'flex',
    backgroundColor: 'rgb(0, 130, 26)',
    width: 140,
    height: 35,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    position: 'absolute',
    zIndex: 2,
    top: 60,
    left: 5,
  },
    notificarAnimadoCardVermelho: {
    display:'flex',
    backgroundColor: 'rgb(255, 14, 23)',
    width: 140,
    height: 35,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    position: 'absolute',
    zIndex: 2,
    top: 60,
    left: 5,
  },
  notificarAnimadoCardOculto:{
    display:'none',
    backgroundColor: '#FE9800FF',
    width: 140,
    height: 35,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    position: 'absolute',
    zIndex: 2,
    top: 60,
    left: 5,
  },
  notificarAnimadoTexto: {
    color: '#ffffff',
    fontSize: 19,
    fontWeight: 700,
    textAlign: 'justify',
  },
  card: {
    width: '99%',
    height: '65%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  image: {
    backgroundColor: '#ffffff',
    width: 350,
    height: '85%',
    borderTopRightRadius: 8,
    borderTopLeftRadius: 8,
  },
  cardResultadoText: {
    width: 350,
    height: 55,
    backgroundColor: '#FE9800FF',
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
  },
  cardResultadoTextVerde:{
    width: 350,
    height: 55,
    backgroundColor: 'rgb(0, 130, 26)',
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
  },
  cardResultadoTextVermelho: {
    width: 350,
    height: 55,
    backgroundColor: 'rgb(255, 14, 23)',
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
  },
  cardBtn: {
    width: '90%',
    height: '25%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnNovoCalculo: {
    backgroundColor: '#FE9800FF',
    width: 180,
    height: 45,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textBtnCalcular: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 600,
  },
  textParagrafo: {
    width: '100%',
    height: 120,
    fontSize: 15,
    textAlign: 'justify',
    fontWeight: 600,
    color: '#ffffff',
  },
});